import { QueryProvider } from "@/components/QueryProvider";
import StyledComponentsRegistry from "@/lib/registry";
import AppProvider from "@/provider/AppProvider";
import { inter } from "@/utils/fonts";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "@repo/ui/global.css";
import { ConfigProvider } from "antd";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "NnyhS Store - Home page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AntdRegistry>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "rgb(233, 69, 96)",
            },
          }}
        >
          <QueryProvider>
            <AppProvider>
              <StyledComponentsRegistry>
                <body className={inter.className}>{children}</body>
              </StyledComponentsRegistry>
            </AppProvider>
          </QueryProvider>
        </ConfigProvider>
      </AntdRegistry>
    </html>
  );
}
