import { QueryProvider } from "@/components/QueryProvider";
import RefreshTokenJob from "@/components/RefreshTokenJob";
import { AuthPopup } from "@/components/auth/AuthPopup";
import { inter } from "@/utils/fonts";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "@repo/ui/global.css";
import { ConfigProvider } from "antd";
import type { Metadata } from "next";
import { Header } from "./layouts/header";

export const metadata: Metadata = {
  title: "NnyhS Store - Home page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AntdRegistry>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "rgb(233, 69, 96)",
            },
          }}
        >
          <QueryProvider>
            <body className={inter.className}>
              <Header />
              {children}
              <AuthPopup />
              <RefreshTokenJob />
            </body>
          </QueryProvider>
        </ConfigProvider>
      </AntdRegistry>
    </html>
  );
}
